[platformio]
src_dir = src

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -DELEGANTOTA_USE_ASYNC_WEBSERVER=0
lib_deps =
  miguelbalboa/MFRC522@1.4.12
  https://github.com/madhephaestus/ESP32Servo/archive/refs/tags/1.1.2.zip
  marcoschwartz/LiquidCrystal_I2C@1.1.4
  ayushsharma82/ElegantOTA@3.1.7
  bblanchon/ArduinoJson@7.4.2
